Repository CMPUT301F21T43/CMPUT-301-Project, pull requests merged in 2021-11, with the labels that each got.

#9 01.01.01; 01.02.01; 01.03.01; 01.04.01; 01.05.01
  CMPUT301Project/app/src/main/AndroidManifest.xml
  CMPUT301Project/app/src/main/java/com/example/GroupProject/AddHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/CustomList.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EditHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/Habit.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/MainActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/ViewHabitActivity.java
  CMPUT301Project/app/src/main/res/drawable/circle_button.xml
  CMPUT301Project/app/src/main/res/drawable/ic_baseline_arrow_back_ios_24.xml
  CMPUT301Project/app/src/main/res/drawable/ic_baseline_done_24.xml
  CMPUT301Project/app/src/main/res/drawable/ic_baseline_edit_24.xml
  CMPUT301Project/app/src/main/res/layout/activity_add_habit.xml
  CMPUT301Project/app/src/main/res/layout/activity_edit_habit.xml
  CMPUT301Project/app/src/main/res/layout/activity_main.xml
  CMPUT301Project/app/src/main/res/layout/activity_view_habit.xml
  CMPUT301Project/app/src/main/res/layout/content.xml
  CMPUT301Project/app/src/main/res/values/strings.xml
Labels: enhancement

#17 01.01.01;01.04.01;01.06.01
  CMPUT301Project/app/src/main/java/com/example/GroupProject/AddHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EditHabitActivity.java
  CMPUT301Project/app/src/main/res/layout/activity_add_habit.xml
  CMPUT301Project/app/src/main/res/layout/activity_edit_habit.xml
Labels: enhancement

#19 Added `Today` tag to main habits list for those habits due today.
  CMPUT301Project/.idea/.name
  CMPUT301Project/.idea/compiler.xml
  CMPUT301Project/.idea/copyright/CMPUT301_Group43_Project.xml
  CMPUT301Project/.idea/copyright/profiles_settings.xml
  CMPUT301Project/.idea/misc.xml
  CMPUT301Project/app/build.gradle
  CMPUT301Project/app/src/androidTest/java/com/example/GroupProject/ExampleInstrumentedTest.java
  CMPUT301Project/app/src/main/AndroidManifest.xml
  CMPUT301Project/app/src/main/java/com/example/GroupProject/AddHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/CustomList.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EditHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/Habit.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/HabitFragment.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/MainActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/ProfileFragment.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/User.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/ViewHabitActivity.java
  CMPUT301Project/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  CMPUT301Project/app/src/main/res/drawable/circle_button.xml
  CMPUT301Project/app/src/main/res/drawable/ic_baseline_arrow_back_ios_24.xml
  CMPUT301Project/app/src/main/res/drawable/ic_baseline_done_24.xml
  CMPUT301Project/app/src/main/res/drawable/ic_baseline_edit_24.xml
  CMPUT301Project/app/src/main/res/drawable/ic_home_background.xml
  CMPUT301Project/app/src/main/res/drawable/ic_home_foreground.xml
  CMPUT301Project/app/src/main/res/drawable/ic_launcher_background.xml
  CMPUT301Project/app/src/main/res/drawable/ic_person_background.xml
  CMPUT301Project/app/src/main/res/drawable/ic_person_foreground.xml
  CMPUT301Project/app/src/main/res/layout/activity_add_habit.xml
  CMPUT301Project/app/src/main/res/layout/activity_edit_habit.xml
  CMPUT301Project/app/src/main/res/layout/activity_main.xml
  CMPUT301Project/app/src/main/res/layout/activity_view_habit.xml
  CMPUT301Project/app/src/main/res/layout/content.xml
  CMPUT301Project/app/src/main/res/layout/fragment_habit.xml
  CMPUT301Project/app/src/main/res/layout/fragment_profile.xml
  CMPUT301Project/app/src/main/res/menu/bottom_nav_menu.xml
  CMPUT301Project/app/src/main/res/mipmap-anydpi-v26/ic_home.xml
  CMPUT301Project/app/src/main/res/mipmap-anydpi-v26/ic_home_round.xml
  CMPUT301Project/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  CMPUT301Project/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  CMPUT301Project/app/src/main/res/mipmap-anydpi-v26/ic_person.xml
  CMPUT301Project/app/src/main/res/mipmap-anydpi-v26/ic_person_round.xml
  CMPUT301Project/app/src/main/res/navigation/nav_graph.xml
  CMPUT301Project/app/src/main/res/values-night/themes.xml
  CMPUT301Project/app/src/main/res/values/colors.xml
  CMPUT301Project/app/src/main/res/values/strings.xml
  CMPUT301Project/app/src/main/res/values/themes.xml
  CMPUT301Project/app/src/test/java/com/example/GroupProject/CustomListUnitTest.java
  CMPUT301Project/app/src/test/java/com/example/GroupProject/ExampleUnitTest.java
  CMPUT301Project/app/src/test/java/com/example/GroupProject/HabitUnitTest.java
  CMPUT301Project/build.gradle
  CMPUT301Project/gradle.properties
  CMPUT301Project/gradle/wrapper/gradle-wrapper.properties
  CMPUT301Project/settings.gradle
Labels: enhancement

#22 Fixed Edit Habits to show which days are active.
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EditHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/ViewHabitActivity.java
Labels: enhancement

#44 Habit events unit testing
  CMPUT301Project/app/src/main/java/com/example/GroupProject/CustomList.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/Habit.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/MainActivity.java
  CMPUT301Project/app/src/main/res/layout/activity_edit_habit.xml
  CMPUT301Project/app/src/test/java/com/example/GroupProject/HabitEventUnitTest.java
  CMPUT301Project/app/src/test/java/com/example/GroupProject/HabitUnitTest.java
  CMPUT301Project/app/src/test/java/com/example/GroupProject/UserUnitTest.java
Labels: testing

#47 05.03.01
  CMPUT301Project/app/src/main/AndroidManifest.xml
  CMPUT301Project/app/src/main/java/com/example/GroupProject/CustomUserList.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/FriendsFragment.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/MainActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/SignInActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/User.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/ViewHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/ViewUserActivity.java
  CMPUT301Project/app/src/main/res/layout/activity_view_user.xml
  CMPUT301Project/app/src/main/res/layout/fragment_friends.xml
  CMPUT301Project/app/src/main/res/layout/user_custom.xml
  CMPUT301Project/app/src/main/res/menu/bottom_nav_menu.xml
  CMPUT301Project/app/src/main/res/navigation/nav_graph.xml
  CMPUT301Project/app/src/main/res/values/strings.xml
Labels: enhancement

#57 Marty
  CMPUT301Project/app/src/androidTest/java/com/example/GroupProject/UserInterfaceTest.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/AddHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/CustomList.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EditHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EmailPasswordActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/FriendsFragment.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/GroupProject.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/MainActivity.java
  CMPUT301Project/app/src/main/res/drawable/circle_button.xml
  CMPUT301Project/app/src/main/res/drawable/ic_home_background.xml
  CMPUT301Project/app/src/main/res/drawable/ic_person_background.xml
  CMPUT301Project/app/src/main/res/layout/activity_add_habit.xml
  CMPUT301Project/app/src/main/res/layout/activity_edit_habit.xml
  CMPUT301Project/app/src/main/res/layout/dialog_signin.xml
  CMPUT301Project/app/src/main/res/menu/bottom_nav_menu.xml
  CMPUT301Project/app/src/main/res/mipmap-anydpi-v26/ic_home.xml
  CMPUT301Project/app/src/main/res/mipmap-anydpi-v26/ic_home_round.xml
  CMPUT301Project/app/src/main/res/mipmap-anydpi-v26/ic_person.xml
  CMPUT301Project/app/src/main/res/mipmap-anydpi-v26/ic_person_round.xml
  CMPUT301Project/app/src/main/res/mipmap-hdpi/ic_home.png
  CMPUT301Project/app/src/main/res/mipmap-hdpi/ic_home_round.png
  CMPUT301Project/app/src/main/res/mipmap-hdpi/ic_person.png
  CMPUT301Project/app/src/main/res/mipmap-hdpi/ic_person_round.png
  CMPUT301Project/app/src/main/res/mipmap-mdpi/ic_home.png
  CMPUT301Project/app/src/main/res/mipmap-mdpi/ic_home_round.png
  CMPUT301Project/app/src/main/res/mipmap-mdpi/ic_person.png
  CMPUT301Project/app/src/main/res/mipmap-mdpi/ic_person_round.png
  CMPUT301Project/app/src/main/res/mipmap-xhdpi/ic_home.png
  CMPUT301Project/app/src/main/res/mipmap-xhdpi/ic_home_round.png
  CMPUT301Project/app/src/main/res/mipmap-xhdpi/ic_person.png
  CMPUT301Project/app/src/main/res/mipmap-xhdpi/ic_person_round.png
  CMPUT301Project/app/src/main/res/mipmap-xxhdpi/ic_home.png
  CMPUT301Project/app/src/main/res/mipmap-xxhdpi/ic_home_round.png
  CMPUT301Project/app/src/main/res/mipmap-xxhdpi/ic_person.png
  CMPUT301Project/app/src/main/res/mipmap-xxhdpi/ic_person_round.png
  CMPUT301Project/app/src/main/res/mipmap-xxxhdpi/ic_home.png
  CMPUT301Project/app/src/main/res/mipmap-xxxhdpi/ic_home_round.png
  CMPUT301Project/app/src/main/res/mipmap-xxxhdpi/ic_person.png
  CMPUT301Project/app/src/main/res/mipmap-xxxhdpi/ic_person_round.png
  CMPUT301Project/app/src/main/res/values/strings.xml
Labels: bug

#58 Changed DateToStart DatePicker to EditTexts.
  CMPUT301Project/app/src/main/java/com/example/GroupProject/AddEventActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/AddHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/CustomEventList.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EditEventActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EditHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EmailPasswordActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/Habit.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/ViewEventActivity.java
  CMPUT301Project/app/src/main/res/layout/activity_add_habit.xml
  CMPUT301Project/app/src/main/res/layout/activity_edit_habit.xml
  CMPUT301Project/app/src/test/java/com/example/GroupProject/HabitEventUnitTest.java
Labels: bug

#64 Fixed empty input on sign in and date for add/edit habits.
  CMPUT301Project/app/src/main/java/com/example/GroupProject/AddHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EditHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EmailPasswordActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/HabitActivityHelper.java
  CMPUT301Project/app/src/test/java/com/example/GroupProject/HabitUnitTest.java
Labels: bug

#67 Changed Date for habit dateToStart to Long for yr, mm, dd.
  CMPUT301Project/app/src/main/java/com/example/GroupProject/AddHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EditHabitActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/EmailPasswordActivity.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/Habit.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/HabitActivityHelper.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/HabitFragment.java
  CMPUT301Project/app/src/main/java/com/example/GroupProject/ViewUserActivity.java
  CMPUT301Project/app/src/test/java/com/example/GroupProject/HabitUnitTest.java
Labels: bug

#72 Changed primary color to teal.
  CMPUT301Project/app/src/main/res/color/chipgroup.xml
  CMPUT301Project/app/src/main/res/color/navbar.xml
  CMPUT301Project/app/src/main/res/layout/activity_add_event.xml
  CMPUT301Project/app/src/main/res/layout/activity_add_habit.xml
  CMPUT301Project/app/src/main/res/layout/activity_edit_event.xml
  CMPUT301Project/app/src/main/res/layout/activity_edit_habit.xml
  CMPUT301Project/app/src/main/res/layout/activity_email_password.xml
  CMPUT301Project/app/src/main/res/layout/activity_main.xml
  CMPUT301Project/app/src/main/res/layout/activity_main_event.xml
  CMPUT301Project/app/src/main/res/layout/activity_view_habit.xml
  CMPUT301Project/app/src/main/res/layout/fragment_profile.xml
  CMPUT301Project/app/src/main/res/values-night/themes.xml
  CMPUT301Project/app/src/main/res/values/colors.xml
  CMPUT301Project/app/src/main/res/values/strings.xml
  CMPUT301Project/app/src/main/res/values/themes.xml
Labels: enhancement

#75 UI tests update
  CMPUT301Project/app/src/androidTest/java/com/example/GroupProject/UserInterfaceTest.java
  CMPUT301Project/app/src/main/res/layout/activity_add_event.xml
  CMPUT301Project/app/src/main/res/layout/activity_add_habit.xml
  CMPUT301Project/app/src/main/res/layout/activity_edit_habit.xml
  CMPUT301Project/app/src/main/res/layout/habit_custom.xml
Labels: enhancement, testing
